package domain.attachment;

public class Video {
    private int id;
    private int idOwner;
    private String title;
    private String description;
    private int duration;
    private String[] image;
    private String[] firstFrame;
    private int date;
    private int addingDate;
    private int views;
    private int localViews;
    private int comments;
    private String player;
    private  String platform;
    private int canEdit;
    private int canAdd;
    private int isPrivate;
    private String accessKey;
    private int processing;
    private boolean isFavorite;
    private int canComment;
    //private int canEdit;
    private int canLike;
    private int canRepost;
    private int canSubscription;
    private int canAddToFaves;
    private int canAttachLink;
    private int width;
    private int height;
    private int idUser;
    private int converting;
    private int added;
    private int isSubscription;
    private int repeat;
    private String type;
    private int balance;
    private String liveStatus;
    private int live;
    private int upcoming;
    private int spectators;
    private LikesInfo likesInfo;
    private RepostsInfo repostsInfo;
}
